### ISSUE TITLE
Final checklist to Chipmunk 3

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1503]
## Major
- [x] 1. search results map on scroll-bar
- [x] 2. filters manager (importing/exporting filters; restoring recently used)
- [ ] 3. (*) dropping recent values (everywhere: filters, commands etc, any inputs)
- [x] 4. exporting selections (from main view)
- [x] 4.1. as text
- [x] 4.2. in original format
- [x] 5. exporting search results (full and selections)
- [x] 6. settings view (at least to configure proxy for updates)
- [x] 7. --- postponed ---
- [x] 8. CLI executing
- [x]    8.1. opening files
- [x]    8.2. installing CLI
- [x] 9. TCP connection (client + holder)
- [ ] 10. Charts:
- [x]    10.1. Show frequency of matches
- [ ]    10.2. Charts by values
- [x]    10.3. Extract values function (rust + ts-bindings)
- [ ] 11. Auto-recovery. Dropping of settings in case of failing to read it (for example after update).
- [x] 12. Fixing of scrolling to the bottom
- [x] 13. Fixing of horizontal scroll bars
- [x] 14. Optimize resizing of sidebar and toolbar
- [ ] 15. Remember sizes of layout (sidebar, toolbar)
- [x] 16. concat
- [ ] 16.1. save recent for concat (commented out for now)
- [x]   16.1 FE
- [x]   16.2 Rust + Node
- [ ] 17. Columns view manipulations: coloring, show/hide, remember a states
- [x] 18. Review storing of search results map (probably do not save indexes into file, as soon as it stored in RAM)
- [ ] 19. get rid of fork-dependencies
- [x] 20. make build "green" withing latest rust version
- [x] 20.1. linux
- [x] 20.2. windows
- [x] 20.3. macos
- [x] 21. Add "About" dialog
- [x] 22. Restore bookmarks on reopening of file
- [x] 23. Add application menu & drag and drop for files
- [x] 24. Show progress on indexing
- [ ] 25. update https://formulae.brew.sh/api/cask/chipmunk.json for the last version
- [x] 26. loading performance issue: starting of applications takes too long (one of the reason is wasm loading, which takes >5s)
- [x] 27. details view - show full row content in toolbar
- [x] 28. PCAP file support on client layer

## Bugs / UI
- [x] B.1. scroll bar isn't visible well
- [x] B.2. last row it cutted  
- [x] B.3. concat with 1 line text files
- [x] B.4. filter colors not applied in main-view when reopening file with filters
- [x] B.5. filter details still showing after removing filter
- [x] B.6. key capture breaks other apps (OS Keybindings not always released)
- [x] B.7. log file isn't created in `~/.chipmunk` (`chipmunk.log`) if it doesn't exist
- [x] B.8. Source color is incorrect in the search view
- [x] B.9. First row on change of source has incorrect source_id. Could be reproduced with `cm streams --stdout "journalctl -b" "cat some_file"`
- [x] B.10. Open any file always triggers concat even a single file selected
- [x] B.11. "red" error "Fail to find corrected position" (client layer)
- [x] B.12. Preset isn't restored on multiple related presets (when the same file was opened within multiple presets)
- [ ] B.13. Open a DLT file with 1 filter `as Any`. Leave the session open and open the same file `as DLT`. Leaves session empty.
- [x] B.14. Shortcuts on mac don't work well (click mac issue)
- [x] B.15. Exporting search results doesn't work
- [x] B.16. Search map not fully updated on stream (for example big DLT file)
- [x] B.17. On updatable stream, search view always redirected to selected row (reproduce: make stream, add search term, select some row in mail view, try scroll search view)
- [x] B.18. SDE isn't shown for processes (stdout grabbing)
- [x] B.19. Processes: cwd doesn't consider

## Tests
- [x] add concat test
- [x] add search map test 
- [x] add extracting values tests
- [x] add exporting test

## Suggestions / UI
- [ ] S.1. remove non-existent files (on click / on load)
- [ ] S.2. show icon/text next to recent files (opened as... text/dlt)
- [ ] S.3. Show in search view results extra rows (count is configurable) after each match. It helps analyze multiline logs

## Postponed
- 7. binary data
- 7.1. detecting binary data on parse level
- 7.2. creating a map of binary data (row, byte { start, end })
- 7.3. extracting binary data "as": allow the user to choose
- 7.4. rendering binary data as images (only in the scope of supported types by the browser)
