### ISSUE TITLE
Concat Usability

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1659]
List of things that are missing in Chipmunk 3 compared to Chipmunk 2 and things that will enhance the user experience overall with the "concat"-feature.

- [x] (Un-) Selecting Files does not work #1657
- [x] "Concat" should be on a separate option in the menu bar #1658
- [x] Give a colored overview of the files #1497
- [x] Reorder files by drag and drop #1496 
- [ ] Search in files #1660
- [x] Sorting not applied to "Open each"/"Concat" on multiple files #1661
