### ISSUE TITLE
Basic charts support on client

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1701]
## Restrictions:
- client requests/gets charts data and store it by itself
- backend (rustcore) doesn't store chart's data

## Functionality
- [x] create chart request
- [x] setup settings of chart: line width, line form, colors
- [x] import/export charts from history/profiles service
- [x] render charts
- [x] manage charts: enable/disable, remove

## Tasks
- [x] Deactivate/Disable - Show/Hide data, Show/Hide y-axis
- [x] Show/Hide `NoData` label
- [x] Show/Hide `IsLoading` label
- [x] Fix data hole after disabling, deactivating and converting

## Discuss
- [x] y-axis label - Formatting for numbers with many digits
- [x] Padding for filters if y-axis of chart is shown
- [x] Scale Type: Common, Single
