### ISSUE TITLE
CLI support on UI

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1729]
## Tasks

- [x] Installation/uninstallation CLI support
- [x] help and description of CLI commands
- [x] converting filters / charts into CLI command 

## Related
- #1730
